# linear agebra

In [1]:
import numpy as np

### vector addition
- use in machine learining for gradient updates or geometric vector operations.

In [2]:

vector_u = np.array([1,2])
vector_v = np.array([3,4])
result = vector_u + vector_v
print(vector_u)
print(vector_v)
print("-----------")
print(result)

[1 2]
[3 4]
-----------
[4 6]


### scalar multiplication of a vector
- used to scalling gradient or controlling vector magnitude(increase its size)

In [3]:
alpha = 3
vector_v = np.array([3,4])
result = alpha * vector_v
print(result)

[ 9 12]


### Dot product
- widely used in ML for similarity measures or linear operations.

In [4]:
vector_u = np.array([1,2])
vector_v = np.array([3,4])
result = np.dot(vector_u,vector_v)
print(result)

11


### Cross Product (3D)
- comminly used in physics and computer graphics.

In [5]:

vector_w = np.array([1, 0, 0])
vector_z = np.array([0, 1, 0])
result = np.cross(vector_w, vector_z)
print(result)

[0 0 1]


### Norm (length) of a vector (Euclidean)
- usefulin optimization and distance computations in ML.

In [6]:
vector_v = np.array([3,4])
result = np.linalg.norm(vector_v)
print(result)

5.0


### Orthogonality condition (dot product is zero)
- Orthogonal condition is critical in linear algebra and ML for understanding independence and basis construction.

In [7]:
vector_1 =np.array([1,2])
vector_2 =np.array([-2, 1])
result = np.dot(vector_1, vector_2)
is_orthogonal = result == 0
print(is_orthogonal)


True


### Matrix addition (A + B)
- used in ML for updating weights and biases or aggregating data.

In [8]:
vector_A = np.array([[1 , 2], [3 , 4]])
vector_B = np.array([[5 , 6], [7 , 8]])

result = vector_A + vector_B
print(result)

[[ 6  8]
 [10 12]]


### Matrix scalar multiplication
- useful in ML for adjusting learning rates or normalization.

In [9]:
alpha = 4 
vector_A = np.array([[1 , 2], [3 , 4]])
result = alpha * vector_A
print(result)

[[ 4  8]
 [12 16]]


### Matrix vector multiplication
it is fundamental in ML for applying weights to inputs.

In [10]:
vector_A = np.array([[1 , 2], [3 , 4]])
x = np.array([5 , 6])
result = np.dot(vector_A, x)
print(result)

[17 39]


### Matrix multiplication
- used in Ml for layer operations in neural networks.

In [11]:
vector_A = np.array([[1 , 2], [3 , 4]])
vector_B = np.array([[5 , 6], [7 , 8]])

result = np.dot(vector_A , vector_B)
print(result)

[[19 22]
 [43 50]]


### Transpose of a matrix
- transpose of matrix flips it over its diagonal, exchanging rows with columns. it is used in ML for switching between data representaions.

In [12]:
vector_A = np.array([[1 , 2], [3 , 4]])
print(f"before transpose :\n {vector_A}")
result = vector_A . T
print(f"after transpose :\n {result}")

before transpose :
 [[1 2]
 [3 4]]
after transpose :
 [[1 3]
 [2 4]]


### Determinant of 2 X 2 matrix
- determinant measures scalling factor of transformation represented by matrix. it used to determine matrix invertibility.

In [13]:
vector_C = np.array([[3 , 8], [4 , 6]])
result = np.linalg.det(vector_C)
print(round((result),1))

-14.0


### Inverse of 2 x 2 matrix
- used in solving of linear equations.

In [15]:
vector_C = np.array([[3 , 8], [4 , 6]])
result = np.linalg.inv(vector_C)
print(result)

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]


### Cramer's Rule
- it is  theoretical method often used for small systems

In [18]:
vec_a = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])
det_a = np.linalg.det(vec_a)

x = [np.linalg.det(np.column_stack([b if i == j else vec_a[:, j] 
                                    for j in range(vec_a.shape[1])])) / det_a
     for i in range(vec_a.shape[1])]
print(x)


[np.float64(1.5999999999999988), np.float64(1.8)]


### Inverse of square matrix
- it is crucial in linear algebra and ML for solving systms of equations

In [19]:
vec_a = np.array([[2, 1], [1, 3]])
result = np.linalg.inv(vec_a)
print(result)

[[ 0.6 -0.2]
 [-0.2  0.4]]


### Determinant of triangular matrix
- deerminant calculations and is useful in decompositions

In [20]:
vec_b = np.array([[2, 1, 0], [0, 3, 4], [0, 0, 5]])
result = np.prod(np.diag(vec_b))
print(result)

30


### rank-Nullity Theorem
- it is fundamental in linear algebra for understanding solutions to systems of linear equations

In [23]:
from numpy.linalg import matrix_rank
vec_c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = matrix_rank(vec_c)
nullity = vec_c.shape[1] - rank
print(rank)

2


### Hadamard (Elementwise) Product
- used in ML for feature-wise scalling or geting

In [24]:
vec_a = np.array([[1, 2], [3, 4]])
vec_b = np.array([[5, 6], [7, 8]])
result = np.multiply(vec_a, vec_b)
print(result)

[[ 5 12]
 [21 32]]


# 58 page