# linear agebra

In [5]:
import numpy as np

### vector addition
- use in machine learining for gradient updates or geometric vector operations.

In [7]:

vector_u = np.array([1,2])
vector_v = np.array([3,4])
result = vector_u + vector_v
print(vector_u)
print(vector_v)
print("-----------")
print(result)

[1 2]
[3 4]
-----------
[4 6]


### scalar multiplication of a vector
- used to scalling gradient or controlling vector magnitude(increase its size)

In [11]:
alpha = 3
vector_v = np.array([3,4])
result = alpha * vector_v
print(result)

[ 9 12]


### Dot product
- widely used in ML for similarity measures or linear operations.

In [12]:
vector_u = np.array([1,2])
vector_v = np.array([3,4])
result = np.dot(vector_u,vector_v)
print(result)

11


### Cross Product (3D)
- comminly used in physics and computer graphics.

In [13]:

vector_w = np.array([1, 0, 0])
vector_z = np.array([0, 1, 0])
result = np.cross(vector_w, vector_z)
print(result)

[0 0 1]


### Norm (length) of a vector (Euclidean)
- usefulin optimization and distance computations in ML.

In [15]:
vector_v = np.array([3,4])
result = np.linalg.norm(vector_v)
print(result)

5.0


### Orthogonality condition (dot product is zero)
- Orthogonal condition is critical in linear algebra and ML for understanding independence and basis construction.

In [16]:
vector_1 =np.array([1,2])
vector_2 =np.array([-2, 1])
result = np.dot(vector_1, vector_2)
is_orthogonal = result == 0
print(is_orthogonal)


True


### Matrix addition (A + B)
- used in ML for updating weights and biases or aggregating data.

In [17]:
vector_A = np.array([[1 , 2], [3 , 4]])
vector_B = np.array([[5 , 6], [7 , 8]])

result = vector_A + vector_B
print(result)

[[ 6  8]
 [10 12]]


### Matrix scalar multiplication
- useful in ML for adjusting learning rates or normalization.

In [18]:
alpha = 4 
vector_A = np.array([[1 , 2], [3 , 4]])
result = alpha * vector_A
print(result)

[[ 4  8]
 [12 16]]


### Matrix vector multiplication
it is fundamental in ML for applying weights to inputs.

In [19]:
vector_A = np.array([[1 , 2], [3 , 4]])
x = np.array([5 , 6])
result = np.dot(vector_A, x)
print(result)

[17 39]


### Matrix multiplication
- used in Ml for layer operations in neural networks.

In [20]:
vector_A = np.array([[1 , 2], [3 , 4]])
vector_B = np.array([[5 , 6], [7 , 8]])

result = np.dot(vector_A , vector_B)
print(result)

[[19 22]
 [43 50]]


### Transpose of a matrix
- transpose of matrix flips it over its diagonal, exchanging rows with columns. it is used in ML for switching between data representaions.

In [25]:
vector_A = np.array([[1 , 2], [3 , 4]])
print(f"before transpose :\n {vector_A}")
result = vector_A . T
print(f"after transpose :\n {result}")

before transpose :
 [[1 2]
 [3 4]]
after transpose :
 [[1 3]
 [2 4]]


### Determinant of 2 X 2 matrix
- determinant measures scalling factor of transformation represented by matrix. it used to determine matrix invertibility.

In [34]:
vector_C = np.array([[3 , 8], [4 , 6]])
result = np.linalg.det(vector_C)
print(round((result),1))

-14.0


In [ ]:
# pages 14